development:
  adapter: postgresql
  encoding: unicode
  database: pixtr_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pixtr_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: pixtr_production
  pool: 5
